---
title: "MP1"
author: "Corrina Pascale"
date: "1/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(openintro)
library(mdsr)
library(RColorBrewer)
library(maps)
```


```{r}

data(state_stats)
glimpse(state_stats)

state_stats_noDC <- state_stats %>%
  filter(fed_spend < 100)

a <- ggplot(data = state_stats_noDC, aes(x = fed_spend, y = poverty, color = med_income))

a + geom_smooth(color = "gray", fill = "tomato") + geom_text(aes(label = abbr, size = med_income), color = "white", check_overlap = TRUE) + ggtitle("Federal Spending vs. Poverty Rate by US State, 2010") + labs(x = "Federal Spending per Capita (USD, in 1,000s)", y = "Poverty Rate (% of State Population)", caption = "Source: Census Quick Facts and InfoChimps (no longer available as of 2020)") + theme_dark()

```

```{r}
states_selected <- state_stats %>%
  mutate(region = tolower(state)) %>%
  select(region, unempl, murder, nuclear)

states_map <- map_data("state") %>%
  inner_join(states_selected)

# Unemployment map
b <- ggplot(states_map, aes(map_id = region)) +
  geom_map(aes(fill = unempl), map = states_map) +
  expand_limits(x = states_map$long, y = states_map$lat) +
  scale_fill_viridis_c() +
  labs(x = "", y = "", fill = "Unemployment\n(%)")

b

a + geom_smooth(color = "gray", fill = "tomato") + geom_text(aes(label = abbr), size = 3) +
  ggtitle("Federal Spending vs. Poverty Rate in the United States, 2010") + 
  labs(x = "Federal Spending per Capita (USD, in thousands)", y = "Poverty Rate", caption = "Source: Census Quick Facts and InfoChimps (no longer available as of 2020)") + 
  theme_dark() + 
  scale_color_gradient(name = "median family income ($)", breaks = c(40000, 50000, 60000, 70000), labels = c("40,000", "50,000", "60,000", "70,000"), low = "white", high = "tomato") 

```


